on: pull_request

name: Backdrop Code Review

jobs:
  runPHPCSInspection:
    name: Run PHPCS Backdrop Code Review
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['5.6']

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up PHP ${{ matrix.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: Git diff
      run: git branch -a
      id: git_diff

    - name: Install backdrop/coder
      run: composer global require backdrop/coder

    - name: Manually Set Installed Paths
      run: ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/backdrop/coder/coder_sniffer

    - name: Code review initiated
      run: ~/.composer/vendor/bin/phpcs --standard=Backdrop ./
