on: pull_request

name: Backdrop Code Review

jobs:
  runPHPCSInspection:
    name: Run PHPCS Backdrop Code Review
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['7.3']

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up PHP ${{ matrix.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: Download Coder review
      run: wget https://github.com/hosef/coder/archive/issue-12-update-php-codesniffer.zip -O ~/coder_review.zip

    - name: Unzip Coder review
      run: unzip ~/coder_review.zip -d ~/

    - name: Install Codesniffer
      run: composer global require squizlabs/php_codesniffer:^3.0

    - name: Manually Set Installed Paths
      run: ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/issue-12-update-php-codesniffer/coder_sniffer

    - name: Code review initiated
      run: ~/.composer/vendor/bin/phpcs --standard=Backdrop ./
