on: pull_request

name: Backdrop Code Review

jobs:
  runPHPCSInspection:
    name: Run PHPCS Backdrop Code Review
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php_version: ['7.3']

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Set up PHP ${{ matrix.php_version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}

    - name: Download Coder review
      run: wget https://github.com/hosef/coder/archive/issue-12-update-php-codesniffer.zip -O ~/coder_review.zip

    - name: Unzip Coder review
      run: unzip ~/coder_review.zip -d ~/

    - name: List
      run: ls -la

    - name: Install Codesniffer
      run: composer install
      working-directory: ~/coder-issue-12-update-php-codesniffer

    - name: Code review initiated
      run: ./vendor/bin/phpcs --standard=./coder_sniffer/Backdrop ./
